default_language_version:
  python: "python3"
exclude: '^src/anki_ocr/deps/'
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "check-yaml"
      - id: "mixed-line-ending"
        args: [ "--fix=lf" ]
        description: "Forces to replace line ending by the UNIX 'lf' character."
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.1.8'
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: "https://github.com/psf/black"
    rev: "23.12.1"
    hooks:
      - id: "black"
